# - name: Crear directorios de VMs
#   ansible.builtin.file:
#     path: "{{ parent_folder }}/'dhcp-server'"
#     state: directory

- name: Crear vm's
  ansible.builtin.shell: |
    VBoxManage createvm --name "{{ item.name }}" --ostype Debian_64 --basefolder {{ parent_folder }} --register
    VBoxManage modifyvm "{{ item.name }}" --firmware bios --boot1 dvd --boot2 disk --boot3 none --boot4 none
    VBoxManage modifyvm "{{ item.name }}" --memory {{ item.memory }} --cpus {{ item.cpus }} --audio-driver none --graphicscontroller vmsvga --vram 16
    VBoxManage createhd --filename {{ parent_folder }}/{{ item.name }}/{{ item.name }}.vdi --size {{ item.disk_size }} --variant Standard
    VBoxManage storagectl "{{ item.name }}" --name "SATA Controller" --add sata --controller IntelAhci
    VBoxManage storageattach "{{ item.name }}" --storagectl "SATA Controller" --port 0 --device 0 --type hdd --medium {{ parent_folder }}/{{ item.name }}/{{ item.name }}.vdi --nonrotational on --hotpluggable on
    VBoxManage storagectl "{{ item.name }}" --name "IDE Controller" --add ide
    VBoxManage modifyvm "{{ item.name }}" --macaddress1 {{item.mac1}}
    VBoxManage modifyvm "{{ item.name }}" --nic1 bridged --bridgeadapter1 {{nic}}
    VBoxManage storageattach "{{ item.name }}" --storagectl "IDE Controller" --port 0 --device 0 --type dvddrive --medium {{ iso_out }}
  loop: "{{vm_list}}"
  when: item.name != "dhcp-server"
  become: false
# - name: Configurar red temporal NAT para instalación
#   ansible.builtin.shell: |
#     VBoxManage modifyvm "{{ item.name }}" --nic1 nat
#   loop: "{{ vm_list }}"
#   when: item.name != "dhcp-server"
