- name: update apt cache
  ansible.builtin.apt:
    update_cache: yes

- name: install dependencies
  ansible.builtin.apt:
    name: snapd
    state: present

- name: install microk8s
  community.general.snap:
    name: microk8s
    state: present
    classic: true

- name: wait until microk8s is ready
  ansible.builtin.command: /snap/bin/microk8s status --wait-ready
  register: microk8s_status
  changed_when: false

# - name: ensure /snap/bin is in PATH
#   ansible.builtin.shell: 'echo "export PATH=$PATH:/snap/bin" >> /etc/profile.d/snap_path.sh'
#   args:
#     creates: /etc/profile.d/snap_path.sh

- name: ensure /snap/bin is in PATH
  ansible.builtin.copy:
    dest: /etc/profile.d/snap_path.sh
    content: |
      export PATH=$PATH:/snap/bin
    owner: root
    group: root
    mode: "0644"

- name: wait a bit for snapd to finish setup
  ansible.builtin.wait_for:
    path: /snap/bin/microk8s
    state: present
    timeout: 120

- name: add user to microk8s group
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: microk8s
    append: yes

- name: ensure kube config dir exists
  ansible.builtin.file:
    path: "/home/{{ ansible_user }}/.kube"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: change ownership of .kube recursively
  ansible.builtin.file:
    path: "/home/{{ ansible_user }}/.kube"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    recurse: yes

- name: enable addons microk8s (ingress)
  ansible.builtin.command: /snap/bin/microk8s enable ingress

- name: enable addons microk8s (metallb) (balanceador)
  ansible.builtin.command: /snap/bin/microk8s enable metallb

- name: enable addons microk8s (hostpath-storage)
  ansible.builtin.command: /snap/bin/microk8s enable hostpath-storage

- name: Crear alias kubectl para microk8s
  ansible.builtin.lineinfile:
    path: "{{ ansible_env.HOME }}/.bashrc"
    line: "alias kubectl='/snap/bin/microk8s kubectl'"
    state: present
    create: yes
    insertafter: EOF
  become: false

- name: Recargar el bashrc para aplicar alias
  ansible.builtin.shell: source {{ ansible_env.HOME }}/.bashrc
  args:
    executable: /bin/bash
  become: false
  changed_when: false
