- name: Crear directorio .kube en el worker si no existe
  ansible.builtin.file:
    path: /home/sysadmin/.kube
    state: directory
    owner: sysadmin
    group: sysadmin
    mode: "0755"
  delegate_to: "{{ item }}"
  loop: "{{ groups['controller'] }}"
  become: true

- name: Guardar la configuración del cluster k8s-master
  ansible.builtin.copy:
    dest: "/home/sysadmin/.kube/.config"
    content: "{{ hostvars['k8s-master'].microk8s_config_content }}"
    mode: "0600"
    owner: "{{ansible_user}}"
    group: "{{ansible_user}}"
  delegate_to: "{{ item }}"
  loop: "{{ groups['controller'] }}"
