- name: Asegurar que el usuario tenga permisos sobre microk8s
  block:
    - name: Agregar el usuario al grupo de microk8s
      ansible.builtin.command: "usermod -a -G microk8s {{ ansible_user }}"
      become: true
      changed_when: false

    - name: Cambiar propietario del directorio .kube
      ansible.builtin.command: "chown -R {{ ansible_user }} ~/.kube"
      become: true
      changed_when: false

- name: Ejecutar microk8s config
  ansible.builtin.command: /snap/bin/microk8s config
  register: microk8s_config
  become: true
  # become_user: "{{ ansible_user }}"

- name: Guardar config en variable global
  set_fact:
    microk8s_config_content: "{{ microk8s_config.stdout }}"

- name: Generar ip para conecatar nodos
  ansible.builtin.command: /snap/bin/microk8s  add-node
  register: add_node

- name: Extraer solo la línea de join con --worker
  set_fact:
    microk8s_join_command: "{{ add_node.stdout | regex_search('microk8s join .* --worker', '\\0') }}"

- name: Mostrar el comando de join
  ansible.builtin.debug:
    var: microk8s_join_command

- name: asignar rol controlplane
  ansible.builtin.command: "/snap/bin/microk8s kubectl label node k8s-master role=controlplane"
  delegate_to: "{{item}}"
  loop: "{{ groups['master'] }}"
