- name: copiar el contexto del build a nuestro host remoto
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/../roles/azure-devops/images/"
    dest: "/tmp/azp-agent-build/"
    mode: "0644"

- name: Verificar que los archivos llegaron al remoto
  ansible.builtin.shell: ls -l /tmp/azp-agent-build
  register: ls_output

- debug:
    var: ls_output.stdout_lines

- name: Construir imagen del agente de Azure DevOps
  community.docker.docker_image:
    name: "camilodevp/azp-agent"
    tag: "latest"
    build:
      path: "/tmp/azp-agent-build"
      dockerfile: azp-agent-linux.dockerfile
    source: build
    state: present
  register: build_output

- debug:
    var: build_output
