- name: Correr el contendor del agente
  community.docker.docker_container:
    name: azp-agent-linux
    image: camilodevp/azp-agent:latest
    state: started
    env:
      AZP_URL: "{{ azure_devops_url }}"
      AZP_TOKEN: "{{ azure_devops_token }}"
      AZP_POOL: "{{ azure_devops_agent_pool }}"
      AZP_AGENT_NAME: "Docker Agent - Linux"
