- name: crear vm's en base a la iso personalizada
  hosts: local
  gather_facts: false
  vars_files:
    - ../vars/main.yml
  roles:
    - common_host
    - vm_box/vm_box_prepare
    - vm_box/vm_box_build
    - vm_box/vm_box_init
