- name: Installar docker en la vm
  hosts: controller
  gather_facts: false
  become: true
  roles:
    - docker
    - azure-devops/login_docker_hub
    - azure-devops/build_image
    - azure-devops/push_image
    - azure-devops/run_agent
